### ISSUE TITLE
Does not allow case-insensitive attribute selectors

### ISSUE THREAD

**Issue by grmoon** [mdevils/css-selector-parser#15]
Per [css docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), an attribute selector with an 'i' at the end should be valid, but is not.

**Comment by mdevils** [comment]
Thanks, I didn't know this. Will you be able to create a pull-request?

**Comment by mdevils** [comment]
Resolved in `2.0.0`
