### ISSUE TITLE
How to define ::highlight() pseudoElement ?

### ISSUE THREAD

**Issue by noyobo** [mdevils/css-selector-parser#29]
- https://developer.mozilla.org/en-US/docs/Web/CSS/::highlight
- https://developer.mozilla.org/en-US/docs/Web/CSS/::part
- https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted

```js
import { createParser, render } from 'css-selector-parser';

describe('parseSelector', function () {
  it('case', function () {
    const parser = createParser({
      syntax: {
        baseSyntax: 'latest',
        pseudoElements: {
          definitions: ['highlight'],
        },
      },
    });
    const parsed = parser('::highlight(rainbow-color-1)');
    expect(render(parsed)).toMatchSnapshot();
  });
});
```
Get an error:
```js
css-selector-parser parse error: Pseudo-element should be the last component of a CSS selector rule. Pos: 11.
ParserError: css-selector-parser parse error: Pseudo-element should be the last component of a CSS selector rule. Pos: 11.
    at fail (/node_modules/.pnpm/css-selector-parser@2.3.1/node_modules/css-selector-parser/dist/cjs/parser.js:94:21)
```

**Comment by mdevils** [comment]
@noyobo could you please provide W3C spec links to the standards where these pseudo-elements are mentioned?

**Comment by noyobo** [comment]
- `:slotted` 
	- https://drafts.csswg.org/css-scoping-1/#selectordef-slotted
- `:part` 
	- https://drafts.csswg.org/css-shadow-parts/#part
	- https://www.w3.org/TR/css-shadow-parts-1/
- `:highlight` 
	- https://drafts.csswg.org/css-highlight-api/#selectordef-highlight-custom-highlight-name
	- https://www.w3.org/TR/css-highlight-api-1/

  I found these documents, is it helpful?  @mdevils

**Comment by mdevils** [comment]
@noyobo thank you!

I will have to completely redo the output AST to support this :)

Expect version 3.

**Comment by mdevils** [comment]
Hey @noyobo, please take a look at new API proposal: https://github.com/mdevils/css-selector-parser/pull/30

It is not yet fixing the issues you've mentioned, but this new API is able to support the new features (unlike the previous API).

**Comment by noyobo** [comment]
Great! 

I understand this will compile

`::highlight(rainbow-color-1)` 

```js
const selector = ast.selector({
  rules: [
    ast.rule({
      items: [
        ast.pseudoElement({
          name: 'highlight',
          argument: ast.string({ name: 'rainbow-color-1' })
        }),
      ]
    }),
  ]
})
```

right ?

**Comment by mdevils** [comment]
@noyobo yes, correct

**Comment by noyobo** [comment]
Do you have an expected completion date?

**Comment by mdevils** [comment]
Hello @noyobo,

Version `3.0.0` was released.

You can use this config with the new version:

```
const parser = createParser({syntax: {...,
    pseudoElements: {
        definitions: {
            String: ['highlight', 'part'],
            Selector: ['slotted']
        }
    }
}});
```
