### ISSUE TITLE
Terget is set to `esnext` in `tsconfig.mjs.json`

### ISSUE THREAD

**Issue by david-ichilov-evinced** [mdevils/css-selector-parser#33]
Hi,

The target is set to `esnext` in `tsconfig.mjs.json`, is it on purpose?
Why not the same target as in `tsconfig.json`?

The problem there is a [Nullish coalescing operator](https://github.com/mdevils/css-selector-parser/blob/c06a769cb59dc349ff5eeb57f79de575af61420a/src/parser.ts#L715), which is passed by esnext, but converted by es5.

**Comment by mdevils** [comment]
Hello @david-ichilov-evinced,

Good point, thank you.

Fixed in `v3.0.1`.
