### ISSUE TITLE
Parsing id / class selectors that starts with a hyphen followed by a number

### ISSUE THREAD

**Issue by coxrichuk** [mdevils/css-selector-parser#35]
@mdevils I thought I would raise this as a separate issue, but in reference to https://github.com/mdevils/css-selector-parser/issues/34

I have tested the following scenarios when using an ID or Class with a hyphen followed directly by a number

```
const { createParser } = require('css-selector-parser'); // v3.0.2

const parse = createParser({ strict: true, syntax: 'selectors-3' });

const selectorWithANumber = parse('#-1');
const selectorWithAHyphen = parse('.-1');
```

Both currently return the ast rather than throwing an error

**Comment by mdevils** [comment]
Fixed in `v3.0.3`.
