### ISSUE TITLE
Unsupported pseudo elements

### ISSUE THREAD

**Issue by jaqba98** [mdevils/css-selector-parser#39]
Hi. I wanted to use your npm but I have a problem. Your parser throws errors when I use ::selection pseudo-element. I looked through your code and I saw that you don't support any pseudo-elements from css 3. Could you fix this issue because I am not able to use your npm. Could you add full support for any css feature.

I mean about [syntax-definitions.ts](https://github.com/mdevils/css-selector-parser/blob/master/src/syntax-definitions.ts#L315) file. line number 315.

**Comment by jaqba98** [comment]
This is good solution (example)

`
pseudoElements: {
    notation: 'both',
    definitions: ['selection']
},
`

**Comment by mdevils** [comment]
Hello @jaqba98. From your issue I didn't understand what exact CSS selector you are trying to parse and what options you are using in order to parse the selector. Could you please provide more details?

**Comment by jaqba98** [comment]
I wanted to parser this css selector:

.example::selection

And this made an error. The same situation was with others css pseudo-element which was not specified in that typescript file which I mentioned in this post.

Chech whether you can parse that css selector: .example::selection

I can fix this and make pull request if you want.
